#message:2F:(Space_0000) {
	New Game[End]
}

#message:2F:(Space_Credits) {
	[Style Inspect]This mod was created by [Color 0x1]Wrymouth[Color 0x0],[BR]
	for the second Paper Mario[BR]
	Modding Jam.[BR]
	[Wait][Next]
	It was created using Merlon,[BR]
	a modding tool created by Alex[BR]
	which makes use of the Paper Mario[BR]
	decomp.[BR]
	[Wait][Next]
	Projectile code by Pronyo[BR]
	[Wait][Next]
	Music[BR]
	All custom music imported by[BR]
	[Color 0x1]Wrymouth[Color 0x0].[BR]
	Songs used:[BR]
	[Wait][Next]
	Boss Battle - Kirby Super Star[BR]
	MIDI created by Killerkirby on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Fighter Encounter - Pokemon RSE[BR]
	MIDI created by Joo *Johnnyz*[BR]
	Buaes on vgmusic.com.[BR]
	[Wait][Next]
	Stage 4 - Gradius[BR]
	Midi created by Sword-Bolt on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Hammer Bros - Super Mario Bros 3[BR]
	Midi created by Jay Reichard on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Password Screen - Mega Man 3[BR]
	Midi created by Justin Morgan on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Options - Star Fox[BR]
	Midi created by Forrest Riedl on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Opening - U.N. Squadron[BR]
	Midi created by [Color 0x1]Wrymouth[Color 0x0].[BR]
	[Wait][Next]
	Title image font: Audiowide[BR]
	[Wait][Next]
	Enjoy!
	[Wait][End]
}

#message:2F:(Space_Retry) {
	[A] Retry[BR]
	[B] Stage Select[BR]
	[Z] Title Screen[End]
}

#message:2F:(Space_Retry_NoCharacterSelect) {
	[A] Retry[BR]
	[Z] Title Screen[End]
}

#message:2F:(Space_IntroStoryTitle) {
	[Color 0x20][Size 24,24]PAPER MARIO[End]
}

#message:2F:(Space_IntroStorySubtitle) {
	[Color 0x20]AND THE LEGENDARY STAR SHIP[End]
}

#message:2F:(Space_IntroStory) {
	Mushroom Kingdom, Date unknown[BR]
	[BR]
	The evil King Koopa has stolen the[BR]
	Star Rod from Star Haven.[BR]
	He imprisoned its guardians, the[BR]
	Star Spirits, and placed them under[BR]
	the protection of various underlings.[BR]
	[BR]
	He used the power of the Star Rod to[BR]
	make himself invincible and seize the[BR]
	castle of Princess Peach, lifting it[BR]
	far up into the sky.[BR]
	[BR]
	The Star Spirits have requested the[BR]
	help of Mario to retrieve the Star Rod[BR]
	and save the princess.[BR]
	[BR]
	On his travels, Mario faced many[BR]
	challenges. One by one, he overcame[BR]
	his struggles and rescued the Star[BR]
	Spirits.[BR]
	[BR]
	Now, he must use their power to[BR]
	travel to the floating castle and put[BR]
	an end to the invincible king's reign.[BR]
	[BR]
	However, there are many challenges[BR]
	hidden within the vast reaches of[BR]
	the cosmos.[BR]
	[BR]
	Will Mario be able to fight his way[BR]
	through? Or will the entire Mushroom[BR]
	Kingdom succumb to Bowser's might?[BR]
	[End]
}

#message:2F:(Space_FishTalk1) {
	[Style Right]So what's any of that got to do[BR]
	with us?[Wait][End]
}

#message:2F:(Space_FishTalk2) {
	[Style Right]Well, y'know, if he succeeds, we[BR]
	can make wishes again...[Wait][End]
}

#message:2F:(Space_FishTalk3) {
	[Style Right]And what exactly would we be[BR]
	wishin' fer?[BR]
	[Wait][Next]
	I dunno about you, but I'm[BR]
	content just sittin' here lookin'[BR]
	at this fish.[Wait][End]
}

#message:2F:(Space_FishTalk4) {
	[Style Right]Yeah, I s'pose yer right...[Wait][End]
}

#message:2F:(Space_FishTalk5) {
	[Style Right]...I changed my mind, this is[BR]
	boring.[BR]
	[Wait][Next]
	I wonder what that Mario guy[BR]
	is up to right now...[Wait][End]
}

#message:2F:(Space_SkipOpening) {
	[START] Skip[End]
}

#message:2F:(Space_CreditsNotif) {
	[Style Inspect]Please read the credits before[BR]
	starting the game.[Wait][End]
}

#message:2F:(Space_OpeningScene1) {
	[Style Right]Alright Mario, welcome aboard the[BR]
	Legendary Star Ship of Star[BR]
	Haven.[BR]
	[Wait][Next]
	It's gonna be a long trip to[BR]
	Bowser's Castle, so I'll quickly[BR]
	explain how to control the vessel.[BR]
	[Wait][Next]
	You can use the joystick to[BR]
	move around.[BR]
	[Wait][Next]
	Try it in this empty area![Wait][End]
}

#message:2F:(Space_OpeningScene2) {
	[Style Right]Ha ha![BR]
	[Pause 10]Found you, Mario![Wait][End]
}

#message:2F:(Space_OpeningScene3) {
	[Style Right]Who was that?[Wait][End]
}

#message:2F:(Space_OpeningScene4) {
	[Style Right]Mario![BR]
	[Pause 10]With my new powers, you won't[BR]
	stand a chance![Wait][End]
}

#message:2F:(Space_OpeningScene5) {
	[Style Right]Oh dear, it looks like the[BR]
	ride to Bowser's Castle won't[BR]
	be as easy as I thought...[BR]
	[Wait][Next]
	Mario, there's one more feature[BR]
	we've added to the Star Ship[BR]
	that you can use to win this[BR]
	battle.[BR]
	[Wait][Next]
	Press [A] to fire a blast of[BR]
	star power![Wait][End]
}

#message:2F:(Space_OpeningScene6) {
	[Style Right]Let's see you dodge this![Wait][End]
}

#message:2F:(Space_CharacterSelectIntro) {
	There are a few more enemies[BR]
	to defeat.[End]
}

#message:2F:(Space_CharacterSelectHammer) {
	This is the Hammer Bros'[BR]
	Chuckster Mobile.[BR]
	HP = 32.[End]
}

#message:2F:(Space_CharacterSelectLakitu) {
	This is Lakithunder.[BR]
	HP = 32.[End]
}

#message:2F:(Space_CharacterSelectWhale) {
	This is a Space Whale.[BR]
	HP = 24.[End]
}

#message:2F:(Space_CharacterSelectKoopa) {
	This is the Koopa Bros. Cruiser.[BR]
	HP = 32.[End]
}

#message:2F:(Space_EnemyDefeated) {
	[InputOff]This enemy has already been[BR]
	defeated![Pause 60][End]
}

#message:2F:(Space_EldstarTalk1) {
	[Style Right]Excellent work, Mario![BR]
	We've finally reached Bowser's[BR]
	Castle![Wait][End]
}

#message:2F:(Space_EldstarTalk2) {
	[Style Right]Hm?[BR]
	[Pause 10]Goombario? [Pause 10]Kooper?[BR]
	[Wait][Next]
	Oh, are you talking about that[BR]
	group that was following you[BR]
	around on Star Haven?[BR]
	[Wait][Next]
	I didn't know they were supposed[BR]
	to tag along...[BR]
	[Wait][Next]
	If they're as important as you[BR]
	say, we'll need to go back for[BR]
	them.[BR]
	[Wait][Next]
	Just hop back into the ship and[BR]
	we'll go get them.[Wait][End]
}

#message:2F:(Space_EldstarTalk3) {
	[Style Right]Oh, I should also mention...[BR]
	[Wait][Next]
	We found a star shaped necklace[BR]
	lying around in Star Haven.[BR]
	[Wait][Next]
	That wouldn't happen to have[BR]
	been yours, would it?[Wait][End]
}

#message:2F:(Space_BadEnding) {
	[Style Inspect]You got the bad ending...[BR]
	[Wait][Next]
	(This one is canon, by the way)[Wait][End]
}

#message:2F:(Space_GoodEnding) {
	[Style Inspect]You got the good ending![BR]
	[Wait][Next]
	But will Mario be able to stop[BR]
	Bowser and save the princess?[BR]
	[Wait][Next]
	idk[Wait][End]
}

#message:2F:(Space_CharacterSelect) {
	[Color 0x5][Size 24,24]SELECT OPPONENT[End]
}
