#message:2F:(Space_0000) {
	New Game[End]
}

#message:2F:(Space_Credits) {
	[Style Inspect]This mod was created by Wrymouth,[BR]
	for the second Paper Mario[BR]
	Modding Jam.[BR]
	[Wait][Next]
	It was created using Merlon,[BR]
	a modding tool created by Alex[BR]
	which makes use of the Paper Mario[BR]
	decomp.[BR]
	[Wait][Next]
	Projectile code by Pronyo[BR]
	[Wait][Next]
	Music[BR]
	All custom music imported by me.[BR]
	Songs used:[BR]
	[Wait][Next]
	Boss Battle - Kirby Super Star[BR]
	MIDI created by Killerkirby on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Fighter Encounter - Pokemon RSE[BR]
	MIDI created by Joo *Johnnyz*[BR]
	Buaes on vgmusic.com.[BR]
	[Wait][Next]
	Stage 4 - Gradius[BR]
	Midi created by Sword-Bolt on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Hammer Bros - Super Mario Bros 3[BR]
	Midi created by Jay Reichard on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Password Screen - Mega Man 3[BR]
	Midi created by Justin Morgan on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Enjoy!
	[Wait][End]
}

#message:2F:(Space_Retry) {
	[A] Retry[BR]
	[B] Stage Select[BR]
	[Z] Title Screen[End]
}

#message:2F:(Space_IntroStoryTitle) {
	[Color 0x20]PAPER MARIO[End]
}

#message:2F:(Space_IntroStory) {
	Mushroom Kingdom, Date unknown[BR]
	[BR]
	The evil King Koopa has stolen the[BR]
	Star Rod from Star Haven.[BR]
	He imprisoned its guardians, the[BR]
	Star Spirits, and placed them under[BR]
	the protection of various underlings.[BR]
	[BR]
	He used the power of the Star Rod to[BR]
	make himself invincible and seize[BR]
	the castle of Princess Peach,[BR]
	lifting it far up into the sky.[BR]
	[BR]
	The Star Spirits have requested the[BR]
	help of Mario to retrieve the Star Rod [BR]
	and save the princess.[BR]
	[BR]
	On his travels, Mario faced many[BR]
	enemies. One by one, he overcame[BR]
	his struggles and rescued the[BR]
	Star Spirits.[BR]
	[BR]
	Now, he must use their power to[BR]
	travel to the floating castle and[BR]
	put an end to the invincible king's[BR]
	reign.[BR]
	[BR]
	However, the vast reaches of the[BR]
	cosmos hide many challenges.[BR]
	[BR]
	Will Mario be able to fight his way[BR]
	through? Or will the entire Mushroom[BR]
	Kingdom succumb to Bowser's power?[BR]
	[End]
}

#message:2F:(Space_FishTalk1) {
	[Style Right]So what's any of that got to do[BR]
	with us?[Wait][End]
}

#message:2F:(Space_FishTalk2) {
	[Style Right]Well, y'know, if he succeeds, we[BR]
	can make wishes again...[Wait][End]
}

#message:2F:(Space_FishTalk3) {
	[Style Right]And what exactly would we be[BR]
	wishing for?[BR]
	[Wait][Next]
	I dunno about you, but I'm[BR]
	content just sitting here looking[BR]
	at this fish.[Wait][End]
}

#message:2F:(Space_FishTalk4) {
	[Style Right]Yeah, I s'pose yer right...[Wait][End]
}

#message:2F:(Space_FishTalk5) {
	[Style Right]...I changed my mind, this is[BR]
	boring.[BR]
	[Wait][Next]
	I wonder what that Mario guy[BR]
	is up to right now...[Wait][End]
}

#message:2F:(Space_CharacterSelect) {
	[Font title]
	SELECT OPPONENT[End]
}
