#message:2F:(Space_0000) {
	New Game[End]
}

#message:2F:(Space_Credits) {
	[Style Inspect]This mod was created by Wrymouth,[BR]
	for the second Paper Mario[BR]
	Modding Jam.[BR]
	[Wait][Next]
	It was created using Merlon,[BR]
	a modding tool created by Alex[BR]
	which makes use of the Paper Mario[BR]
	decomp.[BR]
	[Wait][Next]
	Projectile code by Pronyo[BR]
	[Wait][Next]
	Music[BR]
	All custom music imported by me.[BR]
	Songs used:[BR]
	[Wait][Next]
	Boss Battle - Kirby Super Star[BR]
	MIDI created by Killerkirby on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Fighter Encounter - Pokemon RSE[BR]
	MIDI created by Joo *Johnnyz*[BR]
	Buaes on vgmusic.com.[BR]
	[Wait][Next]
	Stage 4 - Gradius[BR]
	Midi created by Sword-Bolt on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Hammer Bros - Super Mario Bros 3[BR]
	Midi created by Jay Reichard on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Password Screen - Mega Man 3[BR]
	Midi created by Justin Morgan on[BR]
	vgmusic.com.[BR]
	[Wait][Next]
	Enjoy!
	[Wait][End]
}

#message:2F:(Space_Retry) {
	[A] Retry[BR]
	[B] Stage Select[BR]
	[Z] Title Screen[End]
}

#message:2F:(Space_CharacterSelect) {
	[Font title]
	SELECT OPPONENT[End]
}

